### ISSUE TITLE
Yams does not throw for duplicate keys

### ISSUE THREAD

**Issue by kgellci** [jpsim/Yams#178]
I would expect the following yaml structure to be invalid because of duplicate key `bar`

```
foo:
  bar:
    text: "Hello"
  bar:
    text: "World"
```

This instead will process fine and one of the keys will win.

**Comment by jpsim** [comment]
That's actually correct according to the YAML spec. You can confirm this by pasting that yaml content in http://www.yamllint.com/

**Comment by kgellci** [comment]
Darn. I will close the issue.

**Comment by PF93mc8y7erq92qTmTjJBysALa** [comment]
Paste

```
foo:
  bar:
    text: "Hello"
  bar:
    text: "World"
```

into http://www.yamllint.com

Click GO


The text displayed is changed into the following
```

--- 
foo: 
  bar: 
    text: World
```

and the message appears that the yaml (foo bar text world) 



The converted version might be valid yaml but the original apparently was not: the text "Hello" has disappeared.


![sample input in yamllint](https://user-images.githubusercontent.com/2647660/83121028-1985d900-a0d2-11ea-99e9-4136298b0afa.png)
