### ISSUE TITLE
Prefer indentation before flow style array nested in mapping.

### ISSUE THREAD

**Issue by ra1028** [jpsim/Yams#237]
Hi, many thanks for Yams.

I'm using Yams to dump Encodable struct to file via YamlEncoder.
I found a little glitch that the malformed indentation before the flow style array elements that nested in mapping.
This isn't corrupted yaml syntax, but it's preferable to indent it.

## Example
```swift
struct Test: Encodable {
    var foo: String
    var bar: Int
    var dict: [String: [String]]
}

let test = Test(
    foo: "foo",
    bar: 100,
    dict: [
        "baz": ["A", "B", "C"],
        "qux": ["1", "2"]
    ]
)

print(try YAMLEncoder().encode(test))
```
### Current behavior
```yaml
foo: foo
bar: 100
dict:
  baz:
  - A
  - B
  - C
  qux:
  - 1
  - 2
```
### Expected
```yaml
foo: foo
bar: 100
dict:
  baz:
    - A
    - B
    - C
  qux:
    - 1
    - 2
```

## Environments
- Library version: 2.0.0

- Swift version: 5.1

- Xcode version: 11.2.1
