### ISSUE TITLE
Decode Node as Mapping

### ISSUE THREAD

**Issue by acecilia** [jpsim/Yams#242]
Hi:

I can not find a way to easily decode the following yaml:

```yml
firstParty:
- SwiftModule1
  dependencies: [SwiftModule2]
- SwiftModule2
  dependencies: [SwiftModule3]
```

To the following `Struct`:

```Swift
struct Module: Codable {
    let name: String
    let dependencies: [String]
}
```

How can I indicate `Yams` that the first value without key corresponds to the `name` property of the struct?

Thanks!
