### ISSUE TITLE
How to exclude template when decode yaml with anchor

### ISSUE THREAD

**Issue by Whirlwind** [jpsim/Yams#250]
```
.ci_job_template: &ci_job_template
  only:
    - triggers
    - web

patch:
  <<: *ci_job_template
  stage: precheck_build
```
after `YAMS.load`, I get
```
{
  ".ci_job_template": {
    "only": ["triggers", "web"]
  },
  "patch": {
    "only": ["triggers", "web"],
    "stage": "precheck_build"
  }
}
```
I want to exclude the `.ci_job_template`. But I can not check the node whether it is a anchor.
