### ISSUE TITLE
dictionary order not respected

### ISSUE THREAD

**Issue by sbarex** [jpsim/Yams#321]
Hi, I have a problem with this code: 

```swift

var a = [
    "Title": "My Title",
    "Author": "Sbarex",
    "Date": "Sunday, May 30, 2021",
    "Abstract": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum."
] 

let mapYAML: String = try Yams.dump(object: a)
print(mapYAML)
```

When converting the dictionary to a YAML code the element order is not respected:
```YAML
Abstract: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum
  pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor
  rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum.
Author: Sbarex
Date: Sunday, May 30, 2021
Title: My Title
```

Then, when I reconvert the yaml code to a dictionaty the order change again:
```swift
if let l = try Yams.load(yaml: mapYAML) as? [String: Any] {
    for (k, v) in l {
        print("\(k): \(v)")
    }
}
```

```YAML
Title: My Title
Abstract: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum.
Author: Sbarex
Date: Sunday, May 30, 2021
```

I'm using Yams 4.0.6 loaded as Swift Package Manager.

Executing the code multiple time the order can change every time.

**Comment by jpsim** [comment]
In Swift, dictionaries are unordered.

> Dictionaries are unordered collections of key-value associations

From https://docs.swift.org/swift-book/LanguageGuide/CollectionTypes.html

However, if you want to preserve the ordering within Yams you can use the `Node` type instead:

```swift
var a: Node = [
    "Title": "My Title",
    "Author": "Sbarex",
    "Date": "Sunday, May 30, 2021",
    "Abstract": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum."
]

let mapYAML: String = try Yams.dump(object: a)
print(mapYAML)
```

Prints:

```yaml
Title: My Title
Author: Sbarex
Date: Sunday, May 30, 2021
Abstract: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum
  pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor
  rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum.
```
