### ISSUE TITLE
Failed to parse escaping character

### ISSUE THREAD

**Issue by fbp93** [jpsim/Yams#328]
**Description:**

I tried to parse my SwiftLint configuration with Yams, but it's failing due to the characters `\\.` of the regex.

```yml
custom_rules:
  rule_name:
    included: ".*Tests\\.swift"
    name: "Name"
    regex: "(Regex)"
    match_kinds:
      - identifier
    message: "Check something"
```
EDIT: It only works if I use ' instead of ". Is there any reason for that?
