### ISSUE TITLE
Add options to force using quotes for strings encoding

### ISSUE THREAD

**Issue by maximkrouk** [jpsim/Yams#344]
```yaml
templates:
- name: 'TCA'
  description: 'TCA template'
- name: 'MVVM'
  description: ''
  path: 'Deprecated/MVVM'
```

or

```yaml
templates:
- name: "TCA"
  description: "TCA template"
- name: "MVVM"
  description: ""
  path: 'Deprecated/MVVM'
```

Instead of

```yaml
templates:
- name: TCA
  description: TCA template
- name: MVVM
  description: ''
  path: Deprecated/MVVM
```

It's not required, just noticed that I can't control this behavior, but the thing I really would like to be customizable is to add extra indentation like:

```yaml
templates:
  - name: TCA
    description: TCA template
  - name: MVVM
    description: ''
    path: Deprecated/MVVM
```
