### ISSUE TITLE
The problem with encoding floating points

### ISSUE THREAD

**Issue by SpectralDragon** [jpsim/Yams#384]
When I encoding object using YAMLEncoder, then I got a next result

```yaml
    Transform:
      rotation:
        x: 0e+0
        y: 0e+0
        z: 0e+0
        w: 1e+0
      scale:
        x: 1e+0
        y: 1e+0
        z: 1e+0
      position: {}
      _matrix:
        x:
          x: 1e+0
        y:
          y: 1e+0
        z:
          z: 1e+0
        w:
          w: 1e+0
```

My rotation, scale and position object contains a zero values. I don't want to see these not human readable values in yaml file.
When I use a JSONEncoder, all values represents correctly. 

How can I fix that? In YAMLEncoder I can't find options for that.
