### ISSUE TITLE
Emojis get escaped when serializing

### ISSUE THREAD

**Issue by ahartwel** [jpsim/Yams#400]
If a yaml string has emojis inside of it, after running `serialize` they are escaped in the final output.

For example

this:
```
test:
  a_key: "hello 🥹"
  another:
    test: "test"
    test2: "test2"
```

gets turned into
```
test:
  a_key: "hello \U0001F979"
  another:
    test: "test"
    test2: "test2"
```

after going through a Yams.compose -> Yams.serialize cycle. 

Here's a simple repro:
```
let yaml = """
test:
  a_key: "hello 🥹"
  another:
    test: "test"
    test2: "test2"
"""

let node = try Yams.compose(yaml: yaml)
let newString = try Yams.serialize(node: node!, allowUnicode: true)
print(newString)
```
