### ISSUE TITLE
Empty keys cannot be decoded

### ISSUE THREAD

**Issue by ffried** [jpsim/Yams#404]
I have the following YAML:

```yaml
root:
  :
    - sub: value1
  other:
    - sub: value2
```

Which according to [YAML Lint](https://www.yamllint.com) is valid.

But Yams fails to decode it with the following error:

```
2:3: error: parser: while parsing a block mapping in line 2, column 3
did not find expected key:
  :
  ^)))
```
