### ISSUE TITLE
Empty string parsed as <null>

### ISSUE THREAD

**Issue by yonaskolb** [jpsim/Yams#53]
If you try to specify an empty string as a value it's parsed as `<null>` instead of an empty string

yaml file:
```yaml
string1: "string"
string2: string
emptyString: ""
```

```swift
let string = getFile()
let yaml = try Yams.load(yaml: string)
let dictionary = yaml as! [String: Any]
print(dictionary["emptyString"]!) // prints "<null>" instead of ""
```
