### ISSUE TITLE
[CI] Move to CircleCI

### ISSUE THREAD

**Issue by norio-nomura** [jpsim/Yams#64]
Since it is longer to wait for the time to start a new job than the build time, is it better to reduce the number of jobs?

**Comment by jpsim** [comment]
I suggest moving to CircleCI. I did this for SourceKitten, SwiftLint and jazzy. It's _soooo_ much faster. I can take care of doing it for Yams if you'd like.

**Comment by norio-nomura** [comment]
Are you using the free plan of CircleCI provided for open source?
I know CircleCI is very fast, but considering the frequency of development so far, I also think that CircleCI is overspecific to use with Yams. 🤔

**Comment by jpsim** [comment]
Yes’m I’m using their OSS free plan. What do you mean by overspecific?

**Comment by norio-nomura** [comment]
Oh, I made a mistake in writing. I wanted to write it as overspec.

**Comment by norio-nomura** [comment]
> I can take care of doing it for Yams if you'd like.

As I learned that you are using the free OSS plan, I have no reason to refuse your offer. 😊

**Comment by jpsim** [comment]
Ok, I should have time in the next few days.

**Comment by norio-nomura** [comment]
Now, I have been enabled the free OSS plan on CircleCI. 🙂 
I can open a PR adding `circle.yml` after testing on my repo.
Could you please follow Yams on CircleCI?

**Comment by norio-nomura** [comment]
[As far as I tested](https://circleci.com/gh/norio-nomura/Yams/10), it seems CircleCI does not provide testing with Xcode 8.2.1 or earlier.
It seems better to migrate to CircleCI after dropping support Swift < 3.2.

**Comment by jpsim** [comment]
I've enabled CircleCI for this repo. I agree, we should land #43, cut a release, then drop Swift < 3.2.

**Comment by norio-nomura** [comment]
> I've enabled CircleCI for this repo

Thanks! 🙏 
By the way, in order to omit `brew install swiftlint` in CircleCI, I'm trying to make a docker image of swift including swiftlint, but I'm thinking about how to name and tag rules.

I have created `norionomura/swiftlint`, but I can not think of this as a good name:
```yml
  linux_swift_4:
    docker:
      - image: norionomura/swiftlint:0.23.1
    steps:
      - checkout
      - run: swift test
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/
```
I think …:
- `norionomura/swiftlint:0.23.1@swift-4`
- `norionomura/swift+swiftlint:4.0+0.23.1`

Any ides?
