### ISSUE TITLE
Support explicit type conversion from scalar to Swift types by using TAG

### ISSUE THREAD

**Issue by norio-nomura** [jpsim/Yams#7]
It seems `yaml_parser_load()` sets `tag:yaml.org,2002:str` to `yaml_node_s.tag` on both of following:
```yml
---
explicit-string: !!str foo
implicit-string: bar
```
For supporting this over #6, we need to change from using `yaml_parser_load()` to event based parsing.
